- package-lock.json
- package.json
Getting the above error when trying to use the package -> I think that means we need to add `@kinde-oss/kinde-auth-pcke-js` as a dependency
> add pkce dep

- package.json
> bump: kinde pkce version

- package-lock.json
update package lock to match package json
> bump: package-lock

- package-lock.json
- package.json
> bump: pkce js bump version

- package-lock.json
- package.json
update dependency
_Suppose there is a related issue with enough detail for a reviewer to understand your changes fully. In that case, you can omit an explanation and instead include either “Fixes #XX” or “Updates #XX” where “XX” is the issue number._
> dep: update release-it

- package-lock.json
- package.json
Consume latest version of pkce lib
> Update PKCE JS dep

- readme.md
Update README with starter kit link
Fixes: #30 
> Update README with starter kit link

- package-lock.json
- package.json
Bump PKCE version to factor in redirect fix
> chore: bump dep

- .gitignore
- package.json
- readme.md
Add playground for improved DX
> feat: dev playground

- package-lock.json
- package.json
> bump: pkce dep

- package-lock.json
- package.json
- src/state/KindeProvider.tsx
- fix passing `isForceRefresh` to getToken and getIdToken
_Suppose there is a related issue with enough detail for a reviewer to understand your changes fully. In that case, you can omit an explanation and instead include either “Fixes #XX” or “Updates #XX” where “XX” is the issue number._
> fix: passing through options to getToken and getIdToken

- src/components/LoginLink.tsx
- src/components/LogoutLink.tsx
- src/components/RegisterLink.tsx
- src/state/KindeContext.ts
fix: component buttons type
fix: redirectUrl optional on logout
> fix: couple small fixes

- src/state/KindeProvider.tsx
When login or register methods were called with no params, they did not work
> fix: no params passed into auth params

- src/state/KindeContext.ts
Adds state to the login and register interfaces
> fix: interface params for login and logout methods for state

- src/state/KindeProvider.tsx
don't return null and return JSX back
> fix: always return JSX from provider

- package.json
- pnpm-lock.yaml
- src/state/KindeProvider.tsx
updates to support the new js-utils
> deps: update js-utils

- src/state/KindeProvider.tsx
Add support to force the children to be rendered even when not initialised.
> feat: add option to force children render

- renovate.json
- src/state/KindeContext.ts
- src/state/KindeProvider.tsx
- src/state/store.ts
- vite.config.ts
isLoading was getting set to `false` before the code exchange had complete. This removes the false entry and ensures always set to false last
> chore: lint

- package-lock.json
- package.json
Update PKCE SDK to fix active token check
> fix: token active check

- package.json
- pnpm-lock.yaml
Update js-utils to add marketing tag support
> deps: update @kinde/js-utils to 0.14.0

- src/components/LogoutLink.tsx
- src/state/KindeContext.ts
- src/state/KindeProvider.tsx
- src/state/types.ts
Adds support for logout options, including ability to end all session.
> feat: add LogoutOptions and support for logout all sessions

- package.json
- src/state/KindeProvider.tsx
Adds support for re-auth which allows the end user to bookmark auth pages
> feat: support reauth
